### ISSUE TITLE
Change podspec to depend on OpenSSL 1.0.2 and newer

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1034]
Given the long history of OpenSSL having numerous issues it would make more sense to set the podspec to use 1.0.2 and later which are binary compatible with 1.0.1 and would provide more security for users

**Comment by wmathurin** [comment]
In the next version of the Mobile SDK (you can check it out on the unstable branch), we no longer depend on OpenSSL. Open ssl was only needed because of sqlcipher - but in the next version of the Mobile SDK, we are moving to the most recent versions of sqlcipher which uses Apple's CommonCrypto framework for hardware-accelerated encryption.
