### ISSUE TITLE
Programmatic Login

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1115]
Is it possible to provide a username and password, and login WITHOUT using the web view?  Essentially, would like to build test classes but need to provide user/pass to get access.  cc @bhariharan

**Comment by jeffreyjackson** [comment]
cc @brad36

**Comment by bhariharan** [comment]
There is no way to perform authentication without using a ```WebView```. This is due to security requirements that we have. However, it is possible to write live tests that hit an endpoint, as long as an access token is supplied and a user account object is created. Take a look at our ```RestClient``` tests - many of them are live tests.
