### ISSUE TITLE
Support for TLS 1.1 and 1.2 in iOS App using SalesforceMobileSDK

### ISSUE THREAD

**Issue by srikantchonnad** [forcedotcom/SalesforceMobileSDK-iOS#1202]
Hello,
Does Salesforce Mobile SDK version 3.1.0 for iOS support TLS 1.1 and 1.2?

Regards,
Srikant.

**Comment by camilleversteeg** [comment]
I'm curious as well

**Comment by camilleversteeg** [comment]
When can we expect an update? I opened up a case at Salesforce and did not get any answer.

TLS will be disabled next year. Will this impact the Salesforce Mobile SDK? If yes, then which versions?  We have hundreds of users on our mobile application. If they all need to update to a new version, then the impact is huge.

Where can we get these answers?

**Comment by khawkins** [comment]
iOS has supported TLS 1.1 and 1.2 since iOS 5, and the Mobile SDK does not deviate from that default support in any of our network-related code.  Mobile SDK 3.x has a minimum iOS requirement of 7.0, so any apps built with the 3.x version of the SDK should be fine for the necessary TLS support.

I'm going to close this out, but feel free to follow up and/or re-open if you have further questions.

**Comment by camilleversteeg** [comment]
So if I understand you correct:

In case you have iOS 7, 8 or 9 installed and you use Mobile SDK 2.x in your application, you will not be able to login when TLS 1.0 is disabled.

If you the 3.x installed, you are ok.

**Comment by khawkins** [comment]
No, that's incorrect—sorry that I wasn't clear.  To put it another way, the Mobile SDK has _never_ deviated at its core from the network stack provided by Apple/iOS.  So TLS version support is _entirely_ dependent on the iOS version of the device using the app.  As long as your app is targeting iOS 5 or later, any version of the Mobile SDK you use will support TLS 1.1 and 1.2.  It's entirely about the OS version.
