### ISSUE TITLE
Username-Password OAuth Authentication Flow

### ISSUE THREAD

**Issue by rovqapint** [forcedotcom/SalesforceMobileSDK-iOS#1215]
How can we implement Username-Password OAuth Authentication Flow (https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_username_password_oauth_flow.htm) in the app based on SalesforceMobileSDK.

Could you suggest something?

**Comment by wmathurin** [comment]
It's not recommended approach by our security team (because the application gets to capture the password of the user). The preferred approach is the login through a webview where the application only gets refresh/session tokens which can be revoked if need be by an admin.
Why are looking to do a username/password authentication?

**Comment by rovqapint** [comment]
This question related to https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1212
We have setup Single Sign-On in SFDC with "Disable login via "test.salesforce.com".
We need to be able to login with Salesforce Credential only for admins on device too.

**Comment by bhariharan** [comment]
Username-password authentication is not supported by Mobile SDK for security reasons.
