### ISSUE TITLE
When I delete an entry in salesforce sever then sync down, ???

### ISSUE THREAD

**Issue by xzhangyueqian** [forcedotcom/SalesforceMobileSDK-iOS#1397]
Hi guys,

When I delete an entry on salesforce server side then sync down, the local entry of the data **can't be deleted**. But **insert update** is valid.
I had looked up the salesforce iOS SDK, then I do something as follows :
- change `SFSyncStateMergeModeLeaveIfChanged` to `SFSyncStateMergeModeOverwrite` which in SObjectDataManager. it is invalid.
- find what about *full sync down* but I cant't find it.        

Please help me to solve it.
Thanks.

**Comment by wmathurin** [comment]
If entries are deleted on the server or no longer match the sync query, they will not be removed from the local store during a "reSync". In your application, you should either
a) clear the local store, and do a full sync (meaning call syncDown instead of reSync)
b) collect ids in the local store, collect ids from the server, and remove from local stores ids that are no longer on the server.
