### ISSUE TITLE
Blue screen after changing selection in 'choose connection' modal

### ISSUE THREAD

**Issue by doovers** [forcedotcom/SalesforceMobileSDK-iOS#1615]
When I click the gear on the top right of the login screen and change the selection, the 'choose connection' modal disappears but does not return to the login screen. Instead it is stuck on a blue screen...

![screen shot 2016-06-22 at 13 52 24](https://cloud.githubusercontent.com/assets/5927611/16255167/9be8e8ec-388a-11e6-9012-1323b9236223.png)

The only way to get around this is to kill the app and restart. I'm using the latest version of the SDK (4.1.2) but the problem was also in 4.1.1.

**Comment by huminzhi** [comment]
@doovers I am trying to reproduce this with the sample app, so I am able to see a similar blue screen as you mentioned, but for me, I am able to see there is an alert window with error message as below. After I dismiss the message, I am then seeing the same blue screen as you.
So, 2 things here:
1. I am seeing this because I am using a wrong URL: www.salesforce.com, if I use www.salesforce.com/login, I will see the login page. So please first make sure you are using a correct URL 
2. If you are not seeing an alert window as I see, you probably should add some code to show the error code, error message when connect to the host (There must be something wrong).

![simulator screen shot jun 23 2016 4 23 01 pm](https://cloud.githubusercontent.com/assets/992106/16323386/431a3998-395f-11e6-9ddd-6dcb637afa7d.png)

**Comment by doovers** [comment]
Sorry for the delayed response! I only got back to this now. Yeas it was a problem with App Transport security so the issue is now resolved. Thanks for the help.
