### ISSUE TITLE
Completion handler passed to -[SFOAuthCoordinator webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once

### ISSUE THREAD

**Issue by brad36** [forcedotcom/SalesforceMobileSDK-iOS#1925]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.3 (beta build 14E5239e)
4. Device: iPad Pro
5. Steps to reproduce: tapping on "Allow" on the "Allow Access?" page of oAuth
6. Actual behavior: crash
7. Expected Behavior: logs in
8. Error Log: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[SFOAuthCoordinator webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once' crashes on line 1009 of SFOAuthCoordinator.m

**Comment by trooper2013** [comment]
@brad36  This issue has  been fixed. It is available in our dev branch.

**Comment by urthakkar** [comment]
@brad36 we released the fix for this as a patch today, 5.0.1

**Comment by va1bhav** [comment]
@trooper2013 @brad36 
I am using hybrid SDK 4.3.1 in an app which is live in app store. I had to format my MAC and re-setup again due to an issue. I had taken backup of the project.

Now I am trying to run same project, app is getting crashed at 2 places with the same error as described above:
1. Tap on Settings icon on Login page to change server.
2. Tapping on "Allow" on the "Allow Access?" page of oAuth


Version of Mobile SDK Used: 4.3.1
Issue found in Native App or Hybrid App: Hybrid App
OS Version: 11.1/10.3.3
Device: iPhone 6, 7
Actual behavior: crash
Expected Behavior: logs in
Error Log: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[SFOAuthCoordinator webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'

**Comment by va1bhav** [comment]
@trooper2013 Thanks for the response. 
I have not even faced this issue in 4.3.1, and we have the app released with 4.3 only. We are planning an upgrade soon but my question here is : What causes this issue? Is this issue because of building app with latest Xcode?
How can i fix it still using 4.3.1 for now?

**Comment by bhariharan** [comment]
It was a bug in our code that we addressed. Please upgrade to the latest (5.3).

**Comment by palaniveludhayakumar** [comment]
But 5.3 has a whole lot of other bugs and semantic issues that is not letting the app to run after I update it.

**Comment by va1bhav** [comment]
@palaniveludhayakumar I had a similar issue, use Xcode version 9.x to build the iOS project. That fixed the 'app not running after upgrading to SDK 5.3' issue for me.

**Comment by annathomasQB** [comment]
> It was a bug in our code that we addressed. Please upgrade to the latest (5.3).

HI,

Was previously using SalesforceSDKCore version 4.2.0.
Client complained about a duplication issue so we tried updating the SDK to latest version(5.3.1)

Now the issue is, when I try logging in, after the app redirects to the main screen, it gets redirected back to the login screen! 

I tried checking the difference between the two SDK versions..

One difference I was able to track is the number of times SFOAuthCoordinator webView:decidePolicyForNavigationAction:decisionHandler: was called.

In 4.2.0, the method getting called was webView: shouldStartLoadWithRequest:navigationType:
and it was called 7 times, and it entered the if ([[requestUrlString lowercaseString] hasPrefix:[self.credentials.redirectUri lowercaseString]]) block on the 7th time only. 
After that, the dashboard page gets shown..

in 5.3.1, the method webView:decidePolicyForNavigationAction:decisionHandler:  is called 12 times. Here also during the 7th call, the block if ([self isRedirectURL:requestUrl]) is entered into. 
I can also see in simulator at this time the dashboard in the backgroud. But in the next calls, the else-block gets executed and then i see the login screen loaded back in the simulator :/ 

Im sure if the consecutive calls after the 7th call weren't made, the app would work fine.. But i'm not sure what triggers these calls and what leads to the if-block getting entered during the 7th time..

I would like to know how to limit the calls and make sure the last call enters the if block so that the dashboard is shown properly.

**Comment by wmathurin** [comment]
5.3.1 is not our latest version. 6.2.0 is. I don't think the problem you describe exists in 6.2.0.

**Comment by annathomasQB** [comment]
Thanks @wmathurin ...
I've been able to update it after updating MacOS and XCode, but I could see many major changes, as building the code keeps failing even after rectifiying issues. 

Please can you be of help for this particular issue ?

I'm getting the following errors in my AppDelegate.m file : 

1. SmartStore/SalesforceSDKManagerWithSmartStore.h' file not found
2. Use of undeclared identifier 'SFLogger'
3. Use of undeclared identifier 'SalesforceSDKManagerWithSmartStore'
4. No visible @interface for 'AppDelegate' declares the selector 'log:msg:'

I can understand that these refers to deprecated files SFLogger and SalesforceSDKManagerWithSmartStore.h..

But I cant find the replacement files for these.. is any documentation available for the changelogs ? it'd be easier to track from there the changes.. 

Thanks again for your time.

**Comment by annathomasQB** [comment]
Thanks  @bhariharan .. I was able to find them yesterday after searching.. and am going through the changing process. Thanks for your response :)
