### ISSUE TITLE
App's automatically launches login screen without notifying user. 

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#2082]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 10+
4. Device: iPhone
5. Steps to reproduce: Logout from Salesforce
6. Actual behaviour: App's show login screen
7. Expected Behaviour: App must intimation(show message) that session is revoked (auto logged out). 
8. Error Log: NA

Hi All, 
I have found this bug while testing my hybrid application with the latest SDK. When the app is logged out automatically(or session is revoked),  Without any intimation (notification) app loads the salesforce login screen. 

Steps: 
1. Launch the application, enter credentials and set PIN (if configured). 
2. Now go to Salesforce logged in with Admin then  Setup > Administration Setup > Connected Apps OAuth usage 
3. Search for the Connected app used for the hybrid application. 
4. Now count click on the number for column 'user count'.  
5.Click on revoke button in front of the username. 

Actual result - Application loads the salesforce login screen. 
Expected - There should be a notification from the hybrid app to the user that session is revoked. 

@bhariharan Is there any method in SDK classes to override this behaviour (for both Android and iOS)?  
We are looking to show notification instead of directly going to the login screen

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
This is not a bug - this is by design and this is the default behavior due to security reasons. Once the refresh token is revoked, the app should be logged out immediately to prevent access of data. Providing a notification to the user with the option of canceling the operation defeats this purpose. However, there are a couple of customization points in the `Mobile SDK` in this space.
- Android:
As you can see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java#L82), the argument `revokedTokenShouldLogout` can be used to control if the logout should happen automatically or not when the refresh token is revoked. If you set this to `false`, you can show a message and then trigger the logout flow.
- iOS:
`SFAuthenticationManager` has 2 delegate callbacks - `willLogoutUser` and `authManagerDidLogout`. You can register for these callbacks and do what you need to do before and after the logout occurs.

This forum is reserved for issues/bugs identified with our code. Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for queries such as this and any other general discussions.
