### ISSUE TITLE
Excessive Disk Usage When Syncing Data

### ISSUE THREAD

**Issue by mattlacey** [forcedotcom/SalesforceMobileSDK-iOS#2088]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: iOS Hybrid
3. OS Version: 10.3 (Hardware)
4. Device: iPad mini 2
5. Steps to reproduce: Create an app that syncs multiple objects at once, with some having ~20k rows
6. Actual behavior: Sync is crazy slow compared to earlier versions
7. Expected Behavior: Sync shouldn't be slow
8. Error Log:

From what I can see, there's a lot of information being dumped to the debug console (every record) and disk access is going crazy as well. It's pulling about 1MB of data and then spending minutes writing to disk at 3MB/s.

Is there a way to turn off the new analytics for hybrid apps?

![screen shot 2017-06-21 at 3 32 46 pm](https://user-images.githubusercontent.com/1256283/27369938-818bdab8-569d-11e7-83b0-3a4a5ba6e701.png)

**Comment by wmathurin** [comment]
Please have a look at https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2057

Basically to disable logging for SmartSync you need to do:
```
        [SFSyncManagerLogger setLevel:SFLogLevelOff];
```
Unfortunately because of a bug discovered in 5.1, you will also need to cherry pick the following fix until we release our next patch or point release:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2076

**Comment by mattlacey** [comment]
Does this work with hybrid apps? It seems as though the code that initialises the SDK is all in the plugin, and building that seems a bit crazy. Am I correct in thinking the plugin repo needs to be branched and then built from?

**Comment by bhariharan** [comment]
You'll need to fork the `iOS` source repo, cherry-pick the fix in and then run our script to build new binaries of the libraries and replace the existing ones in your app with the new ones.

**Comment by mattlacey** [comment]
Thought so, thanks Bharath, will give it a crack!

**Comment by mattlacey** [comment]
Went through the motions and rebuilt the library: no logging but the disk is still being thrashed and it's still super slow to sync as a result!

I've tried running the SmartSync Explorer and querying all contacts in our org in there (~40k), it shows similar behaviour but it's not as slow, I suspect because it's just syncing one object, our app syncs many objects at once, several of which have tens of thousands of records.

![screen shot 2017-06-22 at 4 35 40 pm](https://user-images.githubusercontent.com/1256283/27420360-fc6d110e-5768-11e7-8ad4-fa766bfbc0ac.png)

There appears to be a huge disparity in the amount of data pulled over the network and the amount of data being read from and written to disk. On my iPad even SmartSync Explorer is painfully slow. In previous versions of the SDK (4.3 and back) this was never an issue, we could sync all our data (full load of 110MB from the server) in a minute or two.

**Comment by wmathurin** [comment]
I'm going to look into it.
I've an idea of where it might come from but want to confirm it first.

**Comment by wmathurin** [comment]
In 5.1, we refactored the sync code to delegate to the target the responsibility of reading and writing  to SmartStore, that way by writing a custom target, one could use a different database or organize the data differently (we are using that power in 5.2 for new sync targets that allow you to sync down or up parent records with their children).

As you can see here:  https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFSyncTarget.m#L154
Records are save one by one. I even left myself a [note](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Target/SFSyncTarget.m#L84) to fix that.
Unfortunately the fix was actually put in after the release went out.

The dev branch has the proper implementation: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SmartSync/SmartSync/Classes/Target/SFSyncTarget.m#L151

5.2 should be released pretty soon but if you don't want to work against dev, we recommend you bring over just the correct implementation for the cleanAndSaveInSmartStore method. I believe you should see performance go back to the level we had before.

**Comment by mattlacey** [comment]
@wmathurin Thanks for that Wolfgang, I'll have a go and pulling that change over now!

**Comment by mattlacey** [comment]
Ok, I can confirm that allowing it to write multiple records at once does fix the issue. Hope the next release of the SDK isn't too far off ;)

**Comment by wmathurin** [comment]
Should be in a few weeks. Closing issue since it's fixed in dev.
