### ISSUE TITLE
SalesforceMobileSDK-iOS Integration in Swift.

### ISSUE THREAD

**Issue by jvashisht** [forcedotcom/SalesforceMobileSDK-iOS#2161]
Please fill out the following details:

Version of Mobile SDK Used: 5.2
Issue found in Native App or Hybrid App: Native
OS Version:10.12.5
Device: simulator
Steps to reproduce: 1. i have installed SalesforceMobileSDK-iOS , i want to use this in my swift project. i followed " http://quintonwall.github.io/add-mobilesdk-to-project/index.html " this link but in the Bridging Header it giving me errors { SalesforceCommonUtils/SFLogger.h } and for all the frameworks in header file please help me out on this. how i can i use SalesforceMobileSDK-iOS in  my swift project. TIA
Actual behavior:
Expected Behavior:
Error Log: no log

**Comment by bhariharan** [comment]
Please follow the instructions listed in our dev guide [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_new_force_project.htm?search_text=swift) to generate a `Swift` app using our CLI `forceios`. The instructions on the blog you're referring to appear to be outdated, since `SalesforceCommonUtils` is a library that hasn't existed in more than 2 years.

**Comment by jvashisht** [comment]
means i cant use SalesforceMobileSDK-iOS for swift ??

**Comment by bhariharan** [comment]
Yes you can. `forceios` is a command line tool that integrates `SalesforceMobileSDK-iOS` into a project. Please read our dev guide for details.

**Comment by jvashisht** [comment]
Thanks for the reply. Everything is  working fine. but can i login into salesforce without going to webview or safari. please reply ASAP i really need to integrate salesforce but without going to webview or safari.
