### ISSUE TITLE
Return NSError on SFSyncState object

### ISSUE THREAD

**Issue by joaomvfsantos** [forcedotcom/SalesforceMobileSDK-iOS#2169]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 10
4. Device: iPhone 6S
5. Steps to reproduce: User SmartSync to syncUp
6. Actual behavior: When sync fails no NSError object is provided
7. Expected Behavior: Be able to read an NSError object when sync fails
8. Error Log: N/A

I think it would be very useful to return the NSError on the SFSyncState object when sync fails. At the moment it only outputs the error to the console.

**Comment by wmathurin** [comment]
Sync will no longer fail for non-network errors. So if some of the records cannot be saved on the server for instance because of some validation errors, the sync will continue. The error returned by the server will be saved on the record in the `__last_error__` field.
After the sync runs, look for records that are still in the dirty state (meaning they have the `__local__` flag still set to 1), check their `__last_error__` field to make send of what happens.

Here is the PR that's bringing this enhancement: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2528

It will be in our next release (6.2).
