### ISSUE TITLE
Mobile App timeout not working

### ISSUE THREAD

**Issue by sahitya8e7** [forcedotcom/SalesforceMobileSDK-iOS#2171]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.3
4. Device: iPhone
5. Steps to reproduce:

- Configure on salesforce Web to set the mobile app timeout at 15 mins.
- Log in to the mobile app.
- Push the app to background (leave it idle)
- Bring the app to foreground after 20 mins.

6. Actual behavior: The session wont timeout.
7. Expected Behavior: The session should time out. The user should be presented with the login screen, where the credentials can be entered for logging in.

8. Error Log:

**Comment by wmathurin** [comment]
At login time, because we use Oauth, we get an access token and a refresh token.
The refresh token allows us to get a new access token when it expires without having to prompt the user again for username / password. That makes the user experience in a mobile application but better than in a mobile browser.
For more on oauth refresh, please read [this](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_refresh_token_oauth.htm).
