### ISSUE TITLE
Feature Request: Cancel in progress sync

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-iOS#2271]
Will Mobile SDK 6.0 come with the feature to cancel in progress sync?

**Comment by wmathurin** [comment]
Dev work for 6.0 is pretty much done at this point, and support for cancel was not added.
However because the Mobile SDK is open source, you could attempt to make the changes yourself (the running of a sync starts [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartSync/SmartSync/Classes/Manager/SFSmartSyncSyncManager.m#L170)). And we would love to get a PR.

**Comment by wmathurin** [comment]
We added APIs to stop/restart syncs in 7.1.
For more information see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_stop_start_sync_operations.htm
