### ISSUE TITLE
Issue with Serialization and Custom APEX Rest

### ISSUE THREAD

**Issue by madmax983** [forcedotcom/SalesforceMobileSDK-iOS#2311]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.1
2. Issue found in Native App or Hybrid App:  ReactNative App
3. OS Version: MacOS 10.12.6 
4. Device: IPhone SE
5. Steps to reproduce:

We are using a custom Apex Rest endpoint. This endpoint uses the Apex JSON.Serailize on an class with a structure similar to the following: 

```
global class Response{
        global boolean success;
        global Map<String, Object> results;
        global Map<String, Object> error;

        global Response(){
            this.results = new Map<String, Object>();
            this.error = new Map<String, Object>();
        }
    }
```
6. Actual behavior: Response from server goes into SFRestAPI.m to line 307, and when parsed comes up with the error: '[0]	(null)	@"NSDebugDescription" : @"JSON text did not start with array or object and option to allow fragments not set." Because the data doesn't get parsed, this gets sent back to React-Native which then displays the error: "RCTJSONStringify() encountered the following error: Invalid type in JSON write (OS_dispatch_Data). 
7. Expected Behavior: Custom ApexREST response is parsed properly.
8. Error Log:

**Comment by wmathurin** [comment]
What does the raw response look like?
Is it the stringified json (something like: "{\"results\":..., \"error\":...}"?

**Comment by madmax983** [comment]
@wmathurin Yes, the raw response is the stringified json. We are then parsing that in the React-Native callback.

This setup is working in prod today with v.5.0 of the whole SalesforceMobileSDK stack (iOS, Android, and ReactNative), and I'm in the process of bumping the versions up for our next iteration when this cropped up.

**Comment by wmathurin** [comment]
We made some changes to the SFNetReactBridge in dev (it will be in our soon to be SDK 6.0 release) so that it handles non json response properly (like we once did).
 
See this [PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2305/files)
Despite the PR's name, it's not just about dealing with binary response, it's also about dealing with string responses (see [here](https://github.com/wmathurin/SalesforceMobileSDK-iOS/blob/0c4b4daf4e6b425c6b9dd23736def7d6734bb818/libs/SalesforceReact/SalesforceReact/Classes/SFNetReactBridge.m#L120)). If a string come back from the server, you should get it without problems and you should be able to json parse it in JavaScript like you did in SDK 5.0.

**Comment by madmax983** [comment]
Awesome, thank you @wmathurin. Will hold off bumping up versions now then, and wait till 6.0  drops.
