### ISSUE TITLE
No async query for smartstore

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-iOS#2329]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: iOS 9.3
4. Device: Simulator
5. Steps to reproduce: Fire 2 queries, a very simple one followed by a very complex one
6. Actual behavior: The simple one always complete after the complex one
7. Expected Behavior: The simple one should finish first
8. Error Log: N/A

I find that all queries are in sequence which is First-In-First-Out

Could we have concurrent query?

**Comment by wmathurin** [comment]
Right now all interactions with a smartstore - both reads and writes - are serialized. 
If you slower query is fetching a lot of data, could you use a smaller page size?

**Comment by kdenz** [comment]
@wmathurin This feature is in need for us too, as it's really slow right now, blocking UI thread severely for our React Native application. Smaller page size is currently not possible, any other suggestions? Thanks~

**Comment by wmathurin** [comment]
@kdenz I think your issue (blocking of the UI thread in react native app) could be addressed by moving processing to a background thread in SFSmartStoreReactBridge (similar to what we did for cordova plugins [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/Plugins/SFForcePlugin/SFForcePlugin.m#L38)).

**Comment by wmathurin** [comment]
React Native invokes native modules methods on a serial GCD queue (one queue per module).
We could relax that (see [here](https://facebook.github.io/react-native/docs/native-modules-ios.html#threading) but SmartStore itself also uses a serial GCD queue (one queue per database) for all db access (through FMDBQueue). That one would be harder to relax (we might need to move off FMDB).

To not block the UI, make sure that you render as much as you can before the database call returns.

Closing the issue since there is no clear path to improve concurrency.
