### ISSUE TITLE
SalesforceSwiftSDK requires SmartStore and SmartSync

### ISSUE THREAD

**Issue by ankitaporwal** [forcedotcom/SalesforceMobileSDK-iOS#2400]
Please fill out the following details:

1. Version of Mobile SDK Used: 
6.0
2. Issue found in Native App or Hybrid App:
Native

Hi,

I've updated my salesforce sdk to 6.0 and my app is in swift. I wasn't using using SmartStore or SmartSync or PromiseKit sdk in 5.3 version but on updating 6.0 it requires these sdks as well as internal dependencies. 

Please suggest if there is some way to remove this dependencies.

Thanks,
Ankita Porwal

**Comment by bhariharan** [comment]
@ankitaporwal Our new `SalesforceSwiftSDK` depends on `SmartSync` and `PromiseKit`. This chain of dependency is intentional. However, if you're using only `SalesforceSDKCore`, you won't need to add pod specs for the new libraries in your app. Also, this forum is reserved for known bugs/issues with our code. For other queries, please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445).
