### ISSUE TITLE
Creating user defined functions in database using SalesforceMobileSDK-iOS

### ISSUE THREAD

**Issue by jeevanandhamr** [forcedotcom/SalesforceMobileSDK-iOS#2813]
Please fill out the following details:

**1. Version of Mobile SDK Used:** SalesforceMobileSDK-iOS 7.0.0
**2. Issue found in Native App or Hybrid App:** Native iOS app
**3. OS Version:** iOS
**4. Device:** All iOS devices
**5. Steps to reproduce:**

I am using **SalesforceMobileSDK-iOS** for building native iOS app that interact with the Salesforce platform.

I want to create a user defined functions in SQLite database for example **RemoveDiacritics**. So that I can query for the data something like below.

`SELECT * FROM employees WHERE RemoveDiacritics(first_name) LIKE 'jose'`

**SmartStore** framework internally uses **FMDatabase** to connect with SQLite database and There is an example given for creating user defined method inside FMDatabase framework, but it was commented out.

**FMDatabase** is not exposed outside of SDK to access it directly. Also I did not find any API in **SmartStore** framework for creating the user defined methods from my project.

Please suggest me if there is any possibility to create the user defined methods in the database through **SmartStore** or something else while using **SalesforceMobileSDK**.

**Note:** We are using Pods for external frameworks and it should not be altered in any case.

**6. Actual behavior:** There is no other way to create user defined functions using SalesforceSDK
**7. Expected Behavior:** User defined functions should be possible to create using FMDatabase in SalesforceSDK
**8. Error Log:**

**Comment by wmathurin** [comment]
SmartStore is hiding the underlying database from the app (e.g. the app doesn't need to know how the data is actually laid out, both when writing or when querying). Exposing UDF would break that encapsulation so we don't have any plans to expose UDF.

In your case, why don't you store the "clean" data (first name without diacritics) in another field. So you would do the "cleaning" when writing to the database, instead of incurring the cost on every query. Furthermore, using a user defined function on the field you are querying by will prevent an index on that field from being used.

**Comment by jeevanandhamr** [comment]
@wmathurin - Thanks for your reply. I will try to clean the data and store it in a separate field as you suggested.
