### ISSUE TITLE
SDK Redirecting to salesforce webview

### ISSUE THREAD

**Issue by hanu** [forcedotcom/SalesforceMobileSDK-iOS#3154]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version: 11
4. Device: IPad
5. Steps to reproduce: 1) Login 2) Click Not You - it will ask you to login again 3)Login 4) Redirecting webVIew
6. Actual behavior:
7. Expected Behavior:It should not redirect to the webview
8. Error Log:

**Comment by wmathurin** [comment]
In step 5, what did you mean by "Click Not You"
<img width="408" alt="Screen Shot 2020-02-25 at 10 20 49 AM" src="https://user-images.githubusercontent.com/1012459/75274912-7fec1a00-57b8-11ea-89fc-327aae720b9b.png">

**Comment by hanu** [comment]
![Simulator Screen Shot - iPad Air 2 - 2020-02-25 at 17 19 33](https://user-images.githubusercontent.com/332682/75293319-f0fcf300-57f3-11ea-9e51-0544536548a8.png)

**Comment by wmathurin** [comment]
I see.
The oauth login flow that takes place in the web view is not under the control of the Mobile SDK (it's all coming from the server). Currently it's not completely mobile friendly. Some of the links like remember me / change password / not you) take you out of the oauth flow and leave you in the regular login page.

**Comment by wmathurin** [comment]
I'm going to close this issue since it's not an issue with the SDK itself but with the server oauth screens.

**Comment by hanu** [comment]
I agree, But here Not you link is not redirecting to the Webview. sign-in link only redirecting to the webview.

**Comment by wmathurin** [comment]
Actually for "not me" that's the correct behavior. 

In a browser, if you are already logged in, and you clicked on the link that brought you to the login page, the actual login page (where you enter credentials) would be skipped and you would be taken directly to the "consent" page. The "not you" link allows you to login as someone else.

In a mobile app, that situation can happens if you use "advanced authentication" because authentication happens in a safari view controller (or more precisely a ASWebAuthenticationSession) instead of an embedded webview.
