### ISSUE TITLE
No podspec found for `SalesforceReact` in `../mobile_sdk/SalesforceMobileSDK-iOS`

### ISSUE THREAD

**Issue by sundariragavan** [forcedotcom/SalesforceMobileSDK-iOS#3172]
When updating the SalesforceMobileSDK-iOS. I'm getting this error

**Comment by wmathurin** [comment]
What versions are you updating from and updating to?
We recommend you install forcereact, generate a new application and move you react native javascript code into it.

**Comment by sundariragavan** [comment]
@wmathurin In my project currently we are using 6.2.0 version. Now i'm updating to latest version

**Comment by wmathurin** [comment]
In 7.0, we moved the SalesforceReact library to the [SalesforceMobileSDK-ReactNative repo](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative) repo which ends up in `node_modules/react-native-force` because of the following dependency in your `package.json`:
```
"react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v8.1.0",
```
See [package.json](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/package.json#L18) of template.

Your podfile should pull that dependency in the following way:
```
pod 'SalesforceReact', :path => '../node_modules/react-native-force'
```
See [podfile](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/ios/Podfile#L46) of template.

**Again I strongly recommend you run forcereact to create a clean application and copy your code into it.**
