### ISSUE TITLE
Is there any user data that is either being collected or tracked?

### ISSUE THREAD

**Issue by murilodag** [forcedotcom/SalesforceMobileSDK-iOS#3273]
As part of the iOS 14 /AppTracking Transparency framework, would like to know if any kind of the user data is collected or Tracked by the Salesforce Mobile SDK iOS.

As mentioned in the Apple (Ref: https://developer.apple.com/support/app-privacy-on-the-app-store/),
below were some of the examples for Tracking:

Sharing device location data or email lists with a data broker.
Placing a third-party SDK in our app that combines user data from the app with user data from other developers’ apps to target advertising or measure advertising efficiency, even if we don’t use the SDK for these purposes. For example, using a login SDK that repurposes the data it collects from the app to enable targeted advertising in other developers’ apps.
The following situations are not considered tracking:

When the data is linked solely on the end-user’s device and is not sent off the device in a way that can identify the end-user or device.
When the data broker uses the data shared with them solely for fraud detection or prevention or security purposes, and solely on our behalf.

1. Version of Mobile SDK Used: latest
2. Issue found in Native App or Hybrid App: native
3. OS Version: all
4. Device: all
5. Steps to reproduce: N/A
6. Actual behavior: N/A
7. Expected Behavior: no PII data being collected or tracked
8. Error Log: N/A

**Comment by bhariharan** [comment]
@murilodag The Mobile SDK framework does not collect any PII data. This forum is reserved for issues/bugs with our code. For other queries, please use `Stack Exchange`.

**Comment by brandonpage** [comment]
Hi @murilodag,

The vast majority of the logging we do uses Apple's OSLog, which never leaves the device.  These logs are there to help you (the developer) understand and trace what the SDK is doing within your app.

We do collect some analytical logs that we use to understand how developers and users interact with the SDK.  **These logs never contain any form of personal identifiable information about the user or any way to trace back to a specific user.**  You have the option of opting out of these logs; but I strongly urge you not to do so because it is our only way to know what features are being used.  For example we log _how_ a user logged in (standard, advanced authentication, community login, etc) not _who_ logged in.  We log if a user is using a Passcode/SmartStore/MobileSync completely anonymously to know where we should be spending our development time.
