### ISSUE TITLE
Update from 7.3 to 8.2 Logout

### ISSUE THREAD

**Issue by scinfu** [forcedotcom/SalesforceMobileSDK-iOS#3274]
1. Version of Mobile SDK Used:  From 7.3 to 8.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 14
4. Device: iPhone 7
5. Steps to reproduce: Login in 7.3 and update library to 8.2
6. Actual behavior: No user is logged after update to 8.2
7. Expected Behavior: ofter ipdate to 8.2 maintains user logged
8. Error Log: 
SFUserAccountIdentity.userId is different from what expected in library 8.2
SFOAuthCredentials in 7.3 is saved with 15 chars but in 8.2 with all 18 and do not match.

7.3
```
- (void)setUserId:(NSString *)userId {
    //ensure we only use the first 15 chars of any user ID,
    //since some sources might set 15 char, some might set 18 char
    NSString *truncUserId = [userId substringToIndex:MIN([userId length], 15)]; 
    if (![truncUserId isEqualToString:_userId]) {
        _userId = [truncUserId copy];
    }
}
```

and in 8.2 is

```
- (void)setUserId:(NSString *)userId {
    if (![userId isEqualToString:_userId]) {
        _userId = [userId copy];
    }
}
```

Thank you

**Comment by bbirman** [comment]
Hi @scinfu, I'm looking into this but haven't been able to reproduce. Where do you see the 15 character ID being used after upgrade? Is it in the SDK code or are you accessing it directly?

**Comment by scinfu** [comment]
Hi @bbirman ,
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v7.3.0/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/OAuth/SFOAuthCredentials.m
Line 251  Version 7.3.0
`NSString *truncUserId = [userId substringToIndex:MIN([userId length], 15)];`

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v8.2.0/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/OAuth/SFOAuthCredentials.m
Line 251 Version 8.2.0 missing truncUserId

So, Any user logged in 7.3.0 will be loggedout because stored user id will not match in 8.2.0

**Comment by bbirman** [comment]
@scinfu I see the difference there but haven't seen it cause logout. Where in the code do you see the stored ID causing an issue? Is there anything in your logs?

**Comment by scinfu** [comment]
Current user will be nil, without a user, accesstoken, refreshtoken, openid jwt user seems be logged out.
How do you get logged user?

**Comment by bbirman** [comment]
I see current user populated here. Even when `result` has a 15 character user ID stored, `[self userAccountForUserIdentity:result];` returns an account because it uses the 18 character version of the stored ID
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/13528cc7acc4144a322fa5b9171093f7358a2c95/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/UserAccount/SFUserAccountManager.m#L1322

**Comment by az-oolloow** [comment]
We have just upgraded our app from 7.3 SDK to 8.3 SDK and in testing installing the app on top of previous version the user is definitely logged out :( we are going to confirm if the line of code is identical to that reported by @scinfu

**Comment by az-oolloow** [comment]
So for us the issue is that the account is not returned from the accounts map does not return an account for retrieved identity here:

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/13528cc7acc4144a322fa5b9171093f7358a2c95/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/UserAccount/SFUserAccountManager.m#L1133

I need to add more debugging logging to my SDK fork, but if i create a 7.3.0 app, add sth like `let loggedIn = UserAccountManager.shared.currentUserAccount?.loginState == UserAccount.LoginState.loggedIn` in my root view controller `viewDidLoad` and put a breakpoint below this line, running the below in the debugger results in `nil`

```
po { let un = try! NSKeyedUnarchiver(forReadingFrom: UserDefaults.standard.data(forKey: "LastUserIdentity")!); un.requiresSecureCoding = false; let k = un.decodeObject(forKey: "LastUserIdentity") as! SFUserAccountIdentity; let dict = UserAccountManager.shared.value(forKey: "_userAccountMap") as! [SFUserAccountIdentity: Any]; dump(dict[k])   }()
```

Now interestingly, the below returns true:

```
po { let un = try! NSKeyedUnarchiver(forReadingFrom: UserDefaults.standard.data(forKey: "LastUserIdentity")!); un.requiresSecureCoding = false; let k = un.decodeObject(forKey: "LastUserIdentity") as! SFUserAccountIdentity; let dict = UserAccountManager.shared.value(forKey: "_userAccountMap") as! [SFUserAccountIdentity: Any]; dump(dict.first!.key == k)   }()
```

And it can be seen that `isEqual:` selector is overriden correctly handling 15 to 18 conversion:

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/13528cc7acc4144a322fa5b9171093f7358a2c95/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/UserAccount/SFUserAccountIdentity.m#L91

So it seems something has gone amiss somewhere inside NSMutableDictionary getting value by key?

I will report more if I find something

**Comment by az-oolloow** [comment]
I can confirm that changing `userAccountForIdentity` method like so fixes the issue:

```
- (SFUserAccount *)userAccountForUserIdentity:(SFUserAccountIdentity *)userIdentity {

    SFUserAccount *result = nil;
    [_accountsLock lock];
    result = (self.userAccountMap)[userIdentity];
    
    if (!result) {
        for (SFUserAccountIdentity* key in self.userAccountMap.allKeys) {
            if ([key isEqual:userIdentity]) {
                result = self.userAccountMap[key];
            }
        }
    }
    
    [_accountsLock unlock];
    return result;
}
```

This is probably not the most optimal which is why I won't submit the PR but it unblocked us in the immediate instance.

**Comment by bbirman** [comment]
@az-oolloow thank you for reporting and for all of the info. So far we haven't been able to reproduce the issue but I'm going to test it out more based on your findings.

**Comment by bbirman** [comment]
@az-oolloow we put the same fix in, thank you for your info & debugging!
