### ISSUE TITLE
No superview for oauth web view invoke [super viewDidLayoutSubviews] in the SFLoginViewController subclass

### ISSUE THREAD

**Issue by ygavrylenko** [forcedotcom/SalesforceMobileSDK-iOS#3326]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.1
2. Issue found in Native App or Hybrid App: Native iOS 
3. OS Version: 14.2
4. Device: Several devices (iPHone 8, Simulator iPhone 11)
5. Steps to reproduce: Starting app when Login screen is loading (about 50% of time)
6. Actual behavior: Login screen loads without porblems
7. Expected Behavior: Login screen crashes
8. Error Log:
I know we had this issue once about 2 years ago but it looks like it came up again.
App has been created with forceios swift template, AppDelegate has been extended with SalesforceLoginViewControllerConfig(), app crashed not always, after initial crash you can start it again (and it would work)

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No superview for oauth web view invoke [super viewDidLayoutSubviews] in the SFLoginViewController subclass'
CoreSimulator 732.18.6 - Device: iPhone 11 (5887A2AB-85DF-49D1-9692-BF48FB247286) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 11
terminating with uncaught exception of type NSException
```

**Comment by wmathurin** [comment]
Did you mean Mobile SDK 8.3? (There is no 8.3.1).
How did you generate your application (how are you consuming the Mobile SDK in your application)?

**Comment by wmathurin** [comment]
Are you referring to https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3095 ?
See my comment [there](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3095#issuecomment-561809670). We recommend you use forceios because it will create the correct AppDelegate/SceneDelegate etc. Alternatively, you can look at the template [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/iOSNativeSwiftTemplate/iOSNativeSwiftTemplate).
