### ISSUE TITLE
Mobile SDK 9.0.0 deprecations

### ISSUE THREAD

**Issue by oleksandrPolukhin** [forcedotcom/SalesforceMobileSDK-iOS#3362]
Hello!
In SDK 7.3.0, we used the methods below from **SFSecurityLockout** class for two purposes:

- to show the user a screen for changing the pin code
- so that after login, before creating a pincode, show the user our custom controller and explain why he needs to create a pincode

Now these methods are deprecated in SDK 8.3 and removed in SDK 9.0, what should we use instead?

```
typedef UIViewController* _Nullable (^SFPasscodeViewControllerCreationBlock) (SFAppLockControllerMode mode,SFSDKAppLockViewConfig *viewConfig);
+ (SFPasscodeViewControllerCreationBlock)passcodeViewControllerCreationBlock;
+ (void)setPasscodeViewControllerCreationBlock: (SFPasscodeViewControllerCreationBlock)vcBlock;
+ (void)setPasscodeViewController:(nullable UIViewController *)vc;
+ (void)presentPasscodeController:(SFAppLockControllerMode)modeValue;
```

**Comment by brandonpage** [comment]
Hi @oleksandrPolukhin,

We are currently working on replacing the passcode feature with a much more modern version; unfortunately the changes did not make the 9.0 release.  We have no alternative API's for you to use because the scenarios you are describing (while valid now) won't be necessary with the new system.  I am very sorry for the unfortunate timing on our part.  It was not our intention to degrade the existing experience, only to provide a better experience for you and your customers.  This will be resolved in a future release.
