### ISSUE TITLE
Could a user logout without cleaning the database?

### ISSUE THREAD

**Issue by Minrit** [forcedotcom/SalesforceMobileSDK-iOS#3368]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: iOS 14
4. Device: iPhone 12 Pro Max
5. Steps to reproduce: Log out the app and then log in.
6. Actual behavior: The database is cleaned
7. Expected Behavior: The data is kept.
8. Error Log:

**Comment by bhariharan** [comment]
Currently, all user data is wiped when that user is logged out. This is for security reasons, and by design. However, if you have global non-sensitive data that's not specific to a user, that you would like to save, you can use a global store for that. The app would be responsible for cleaning that data.

Please post general queries on Stack Exchange. This forum is reserved for bugs/issues with our code.
