### ISSUE TITLE
Pin-Code security page neglects to fill in the blue circle on the 4th pin digit after success

### ISSUE THREAD

**Issue by ferrerod** [forcedotcom/SalesforceMobileSDK-iOS#3371]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native iOS iPad
3. OS Version: iOS / iPad OS 14.4
4. Device: Simulator and real iPad Pro
5. Steps to reproduce: login using Sales Force Pin Security and notice 4th digit circle does not get filled in.
6. Actual behavior: 4th pin code circle is still hollow (unfilled)
7. Expected Behavior: 4th pin code circle should be filled in
8. Error Log:

**Comment by brandonpage** [comment]
Thank you for reporting.  If I remember correctly this happens because we dismiss the view controller before the animation finishes and I don't think it is worth delaying just to see the bubble fill in.  Success or failure is made very clear to the user.  This is a very small fit and finish issue in my opinion and I do not think it will be fixed since we are planning to modernize the Passcode feature in a major was in an upcoming release.
