### ISSUE TITLE
Even if I select remember me option, if I logged out form the connected app.

### ISSUE THREAD

**Issue by pushp1010** [forcedotcom/SalesforceMobileSDK-iOS#3389]
Please fill out the following details:

1. Version of Mobile SDK Used:  Latest
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: iOS 14.5
4. Device: Any iPhone 
5. Steps to reproduce: 

> > Login into app.
>>> Don't forgot to select "Remember Me" button
>>>> logout. 
>>>>>>Remember me functionality does not works 

6. Actual behavior: **Remember me** functionality is not working in iOS
7. Expected Behavior: **Remember me** functionality should be working in iOS As it should show the username and password preloaded on the screen
8. Error Log: No logs available

**Comment by wmathurin** [comment]
We don't want to store the password on the mobile device.
The remember me option should not be shown when doing a login flow on a mobile device. Our server authentication team is aware of the issue but has not committed to a date for a fix.

**Comment by pushp1010** [comment]
> We don't want to store the password on the mobile device.
> The remember me option should not be shown when doing a login flow on a mobile device. Our server authentication team is aware of the issue but has not committed to a date for a fix.

>> If we don't want to save password on mobile device. It will be better if we have remember username/ email address which I believe is doable solution and it will save users time when they login again. this won't come as any kind of security issue either for user or Salesforce SDK team.

**Comment by wmathurin** [comment]
One thing you could try is using Mobile SDK advanced authentication (see [doc](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm#:~:text=By%20default%2C%20Mobile%20SDK%20automatically,in%20most%20Mobile%20SDK%20apps.)).
When using advanced authentication, login happens in an ASWebAuthenticationSession is used instead of WKWebView.
ASWebAuthenticationSession supports "password auto-fill" (see [doc](https://developer.apple.com/documentation/security/password_autofill)) - therefore giving you the streamlined login experience you are looking for.
