### ISSUE TITLE
Is there anyway to use our own screen instead of ScreenLockUIView

### ISSUE THREAD

**Issue by PPunya** [forcedotcom/SalesforceMobileSDK-iOS#3450]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.0
2. Issue found in Native App or Hybrid App: Native iOS app
3. OS Version: iOS 14, 15
4. Device: iPhone 8 through 13
5. Steps to reproduce: 
          Launch app; When it asks for passcode, switch to other app to mimic that user does not unlock their device lock; 
6. Actual behavior: 
           Then ScreenLockUIView screen is shown.
7. Expected Behavior:
           Is there anyway we can have our own screen in place of ScreenLockUIView
8. Error Log:
           There is no error.
9. Attachment:
             Attached current screenshot of ScreenLockUIView. Have used fallbackIcon instead of our app icon to maintain confidentiality.
<img width="471" alt="Screen Shot 2021-12-02 at 1 57 54 PM" src="https://user-images.githubusercontent.com/68283420/144395119-94bcc156-c1b4-477f-add2-6555cd18443e.png">

**Comment by PPunya** [comment]
Hi Team,

Appreciate a response to this. It's a bit urgent for our project.

**Comment by brandonpage** [comment]
@PPunya sorry for the slow reply. 

This is by design.  Passcode/ScreenLock is only used by a very small percentage of customers and I don't think we have ever heard of customers extending/customizing it.  

If there is sufficient demand we are open to implementing some sort of customization or extensibility.  Would your preference to be to completely replace the UI by implementing/conforming to some interface/protocol or simply being able to customize the colors/text/icons/etc? 

P.S.  Is the image above from your app or one of our samples?  The Salesforce logo icon should only be shown as a fallback if your app icon cannot be retrieved.

**Comment by PPunya** [comment]
Hi @brandonpage thank you for the response.

Actually we want to reposition Logout and Retry Unlock buttons, use a different icon which is not our app icon, and want to have a different background color with few gradients to match theme of our app. For example something like the screenshot in this news article https://www.nytimes.com/2021/07/28/technology/robinhood-ipo-share-price.html

Having interface to customize color, text, icon, button title, hiding button(s) is good, but as we need to change placement of buttons, it would be better to completely replace the UI with interface for button actions.

**Comment by wmathurin** [comment]
We have just released Mobile SDK 11.0 which contains enhancements in that area (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3586). It's a different user experience, the unlock sheet pops up over the login screen (which you has always been customizable).
![bio_auth_demo](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/1012459/8e5e652c-3a87-4adb-b4a6-d1252c7b4276)

Please re-open this issue if you feel that it still does not address your needs.
