### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by rakesh2007** [forcedotcom/SalesforceMobileSDK-iOS#3481]
Please fill out the following details:

1. Version of Mobile SDK Used: Using-SFOAuthCoordinator, SFOAuthCredentials
2. Issue found in Native App or Hybrid App:- Native App
3. OS Version: iOS 15
4. Device:-iPad
5. Steps to reproduce:
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-02-16 at 00 03 12](https://user-images.githubusercontent.com/7794483/154126564-c6d76e63-44ef-4042-b812-2ba7e4e2afaf.png)

6. Actual behavior:--We have integrated the Salesforce SSO in our iOS application. Everything runs good on login and after login, but when we click on the logout button, the screen is not navigating back to the login page asper the design. (It is taking to the Salesforce allow page). This issue is happening only for the first time login. Second login onwards, navigation are works as per the design without any issue.
7. Expected Behavior:--  Once we logout the.  screen. should go on login page not salesforce allow page.
8. Error Log: Logout issue
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-02-16 at 00 03 12](https://user-images.githubusercontent.com/7794483/154127001-f1c3b472-a900-40ea-acba-02d986918e7f.png)

**Comment by wmathurin** [comment]
During login, there are **short term** cookies being setup which are not tied to the main session and are not invalidated if you logout right away. As a result, if you login then logout **shortly after**, you will skip the first screen where you enter your credentials and find yourself directly into the allow/deny screen.
This issue happens **only when using advanced authentication**, because the login flow takes place in a ASWebAuthenticationSession. With regular authentication, we use a fresh WebView every time and therefore don't have any left over cookies.

The issue is known but won't get addressed since is mostly run into when testing (going through login to logout rapidly).
