### ISSUE TITLE
Multiple bootconfig.plist for Staging / Production Switch

### ISSUE THREAD

**Issue by EBJanHendrik** [forcedotcom/SalesforceMobileSDK-iOS#3502]
Dear experts,

I need to switch between STAGING and PRODUCTION servers during runtime (logged out users). My problem is to change the `ClientId`. Changing the login host `UserAccountManager.shared.loginHost ="some host` is fine. So far, I implemented:

```
 let bootconfig = BootConfig.init("bootconfig-debug.plist")
 SalesforceManager.shared.bootConfig = bootconfig
```

But, in any case the `SalesforceSDKManager` in Line 329  `(SFSDKAppConfig *)appConfig` will be always `nil` and the `SalesforceSDKManager` init the app config via default `bootconfig.plist`. Further more, the `SFUserAccountManager` will set the `defaultAuthRequest` within these params. 

Do I have here a missunderstanding of the SDK and is there a different way to change the `bootconfig` or `ClientID` during runtime or is this an issue?

**Comment by bhariharan** [comment]
Not allowing `bootconfig` to be switched at runtime is by design, since each mobile app must have a `1:1` mapping with a connected app, so that admins can administer security policies for the mobile app. Connected apps are available across every org, and you can administer different  policies for the same connected app on sandbox and production if you'd like to. You should be able to use the same `consumerKey` for both sandbox and production.
