### ISSUE TITLE
Question about differences in networking between version 7 and 9.1. 

### ISSUE THREAD

**Issue by Lyubinets** [forcedotcom/SalesforceMobileSDK-iOS#3512]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 14.4.1
4. Device: iPad.
Hi, I have a question about the differences in networking between version 7 and 9.1. 
After updating SDK from 7 to 9.1 we found that the tool for tracking network requests is not capturing all requests. We are using AppDynamics tool for that. I did some investigation and it looks like nothing changed in our mobile app and AppDynamics library.
In general, I still see network requests like login.salesforce.com/services/oauth2. Other requests like naz.my.salesforce.com/services/data are not tracked anymore. 
Can it be related to some changes in SF MobileSDK or there were no changes related to working with network requests?
Thanks.

**Comment by wmathurin** [comment]
The low level class responsible for sending requests over the wire is SFNetwork.
Since [this change](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/20bf5a2a3ddd75f1626a37db0fe55d17a3801946) that came in 7.3, we send requests auth requests, custom host requests and instance host requests using different NSURLSession. See that [lines](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/20bf5a2a3ddd75f1626a37db0fe55d17a3801946#diff-d19e19adcb0a01e1e71d3f7bf979be23355da3011f8880cc2112b71bb877b928R273) in particular.
Maybe that is confusing AppDynamics?

**Comment by gkotula** [comment]
Hi @Lyubinets Were you able to narrow down the issue after looking at the provided resources?

**Comment by gkotula** [comment]
Closing due to lack of response.
