### ISSUE TITLE
RequestType enum not marked public

### ISSUE THREAD

**Issue by gmckenzi** [forcedotcom/SalesforceMobileSDK-iOS#3556]
The iOS SDK has some very helpful methods for sending composite requests; these methods are marked public and are located in the MobileSync module under Classes/Util/CompositeRequestHelper.swift.

Unfortunately the public functions defined in this file take requests with an enum RequestType that is defined in the file without a visibility qualifier (not marked public). Thus the enum is considered to be internal to the module and none of the valuable public API defined in this file can be used by apps.

**Comment by bbirman** [comment]
@gmckenzi could you point me to the methods you're trying to use? I see [these public ones](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/c27cc1cf484cc1a1373b614757ae54dadd0edb03/libs/MobileSync/MobileSync/Classes/Util/CompositeRequestHelper.swift#L248-L266) but it looks like they only use RequestType internally instead of having it as a parameter

**Comment by wmathurin** [comment]
Closing for lack of responses.
