### ISSUE TITLE
Dynamic SOQL query using usersyncs.json file update WHERE clause

### ISSUE THREAD

**Issue by adijazz91** [forcedotcom/SalesforceMobileSDK-iOS#3579]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App: Native App(Objective-C)
3. OS Version: 15.0
4. Device: iPhone 13
5. Steps to reproduce: Just try to run MobileSyncExplorerSwift workspace
6. Actual behavior: SPQL query is hard coded.
7. Expected Behavior: Need to Dynamically Update and SOQL query internally inside the code.
8. Error Log: {
      "syncName": "syncDownUser",
      "syncType": "syncDown",
      "soupName": "User",
      "target": {"type":"soql", "query":"SELECT Id, Username, ContactId, AccountId, StateCode, RoleDevName__c, LastModifiedDate FROM User WHERE Id = '%@'"},
      "options": {"mergeMode":"OVERWRITE"}
    } 

how can I pass the value of WHERE Clause in this SOQL query, objective-C?

**Comment by wmathurin** [comment]
A given sync definition is not supposed to change otherwise it is not possible to define the "delta sync" behavior. 
You can however programmatically create new syncs, you don't have to use the static config files.
For more information check out the documentation: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_sync_down.htm
