### ISSUE TITLE
SFOAuthCoordinator handleWebServerResponse: URL has no query string.

### ISSUE THREAD

**Issue by sheryDiplomat** [forcedotcom/SalesforceMobileSDK-iOS#3659]
we trying to update SDK version to latest.
after update we have issue login in.
we have custom community login page, 
after login we have salesforce allow page and after it we get the following error:
SFOAuthCoordinator handleWebServerResponse: URL has no query string.

can you give me direction what could it be?

**Comment by bbirman** [comment]
What's the value for appUrlResponse [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/e71cc461bf4f7994b09c3af46e63d63f1822a65b/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/OAuth/SFOAuthCoordinator.m#L288)? Are there any other error logs before that?

**Comment by sheryDiplomat** [comment]
appUrlResponseString is _NSCFString *	@"sfdc://success/ios#access_token=00D1q0000004iJa%21AQkAQO.ZSfUW2KPE4kz.a32VvoynRF_E9mPTqjnUss7AjLpSMAfjvs_emJFBbJFf6y9LT76.FjMJy8OsZ6hYSg_8EZh5BDI&refresh_token=5Aep861xVpGwg47FiJuHJOIYo04Nc6eIWSCVCGU.EQ4uRAaBdCo1epp3ZhIwQabVAxqaKvNe1._QMK1NJdJWqvo&instance_url=https%3A%2F%2Fdiplomat--qa.sandbox.my.salesforce.com&id=https%3A%2F%2Ftest.salesforce.com%2Fid%2F00D1q0000004iJaEAI%2F0051q000007uk8rAAA&issued_at=1699257856230&signature=P%2B53c%2Bn66yultzLf%2Bfv0joE716QaBdoAgBhMYFrUHfQ%3D&sfdc_community_url=https%3A%2F%2Fdiplomat--qa.sandbox.my.site.com&sfdc_community_id=0DB24000000PBhBGAW&scope=api+web+refresh_token&token_type=Bearer"

and then the query is nil

**Comment by sheryDiplomat** [comment]
Hi,
Any ideas?

**Comment by bbirman** [comment]
In 11.0 we added support for the web server auth flow and made it the default instead of user agent (more info [here](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/oauth_web_server_flow.htm)), but it looks like you're getting a user agent response. Could you try setting the web server flag to false?

Swift: `SalesforceManager.shared.useWebServerAuthentication = false`
Objective-C: `[SalesforceSDKManager sharedManager].useWebServerAuthentication = NO;`
