### ISSUE TITLE
Can't Connected to the server : Invalid client Credentials

### ISSUE THREAD

**Issue by MoinJanjua** [forcedotcom/SalesforceMobileSDK-iOS#3716]
1. Version of Mobile SDK Used: 12.0.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 17.0
![Simulator Screenshot - iPad (10th generation) - 2024-05-23 at 12 45 11](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/assets/52666065/0a11067a-37de-4e9d-afec-5fa9199304b3)

4. Device: iPad 11
5. Steps to reproduce: I installed the app after upgrading SDK from 10.0.0 to 12.0.1 and try login than app displaying alert "Can't Connected to the server : Invalid client Credentials"
6. Actual behavior: after upgrading sdk and try login than   app displaying alert "Can't Connected to the server : Invalid client Credentials"
7. Expected Behavior:User able to login 
8. Error Log: No error log

**Comment by wmathurin** [comment]
Starting in MSDK 11.0, we are using web server flow during login (instead of user agent flow). You have to make sure the “Require Secret for Web Server Flow” checkbox is deselected in your connected app. Alternatively, you can programmatically opt out of web server flow and keep using user agent flow.

For more information see: https://developer.salesforce.com/docs/platform/mobile-sdk/guide/oauth-web-server-flow.html

**Comment by MoinJanjua** [comment]
@wmathurin  Thanks Its working
