### ISSUE TITLE
Public headers should use forward class declarations instead of imports

### ISSUE THREAD

**Issue by NachoMan** [forcedotcom/SalesforceMobileSDK-iOS#882]
Each public header exposed from the framework, when requiring cross-header references, should use forward class declarations as opposed to directly importing the headers.  This greatly simplifies dependency management when defining public vs private headers.

If you need to reference a class or protocol from a public header, but that target class isn't marked as public, this can cause a "pulling a thread on a sweater" sort of situation where it forces you to mark more headers public than you'd originally want to.

Furthermore, if those classes are defined in a different dependent library, this causes compiler errors when you attempt to use these libraries in a dynamic framework, since cross-framework imports are disallowed in non-core frameworks.

**Comment by khawkins** [comment]
I agree with this for header references that wouldn't otherwise be public.  For headers that need a public scope anyway, I often prefer to import them in the public headers wher their classes are referenced, as it's a benefit to the consumer.

Take `SFUserAccountManager` and `SFUserAccount`, for example.  If I'm using the former, I'm almost certainly using the latter as well.  But if I declare `SFUserAccount` as a forward class declaration in `SFUserAccountManager`, then my consumers have to include two header files instead of one, everywhere they use the manager class.

We try to be judicious about how we import headers in the Mobile SDK, but I'm sure there's room for improvement.

**Comment by mgetzbw** [comment]
@khawkins I would move towards a more framework based approach, that would simplify build times and reduce the amount of pain (also better cocoapods and swift support)

**Comment by huminzhi** [comment]
moving towards framework based approach
